# Generated by Django 5.2.5 on 2025-12-05 04:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("sku", models.CharField(max_length=50, unique=True)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("ubicacion", models.CharField(blank=True, max_length=100, null=True)),
                ("stock", models.IntegerField(default=0)),
            ],
        ),
    ]
