# Generated by Django 5.2.5 on 2025-12-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('transito', 'Transito'), ('alistamiento', 'Alistamiento'), ('por_verificar', 'Por Verificar'), ('rechazado_x_verificar', 'Rechazado x Verificar'), ('verificado', 'Verificado'), ('empacado_x_despacho', 'Empacado x Despacho'), ('despachado', 'Despachado'), ('despachado_x_facturacion', 'Despachado x Facturacion'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('produccion', 'Produccion'), ('bordado', 'Bordado'), ('dropshipping', 'Dropshipping'), ('compra', 'Compra'), ('anulado', 'Anulado')], default='transito', max_length=40)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('productos', models.JSONField()),
            ],
        ),
    ]
